### PR TITLE
fix: use same entity icons rules as home assistant frontend

### LINKED ISSUE #87: Motion Senor Icon in Chip Cards
Currently, when a motion sensor entity is added to a chip card, it defaults to a `checkbox-marked-circle` icon. The out of box icon for a motion sensor depends on its state, using either `motion-detector` or `motion-sensor-off`. It would be great if this was also the default behavior in Mushroom

### LINKED ISSUE #125: Display correct icons for covers
**Describe the bug**
Covers that have device type set to awning, door or gate are showing incorrect icon to close or open it

**To Reproduce**
Use any cover with device type set to awning, door or gate

**Expected behavior**
The close icon should be arrow-collapse-horizontal and the open icon should be arrow-expand-horizontal as HA does

**Screenshots**
imagen

### LINKED ISSUE #145: Entity card is not using the icon from the device class
**Describe the bug**
I have window sensors that are binary sensors with a device class of `window`.
In the default HA card and in the entity list, they have a window icon that changes with the state of the sensor.
The mushroom entity card is instead showing a checkmark as the icon

**To Reproduce**
1. Add a binary sensor with device class `window`
2. Add a entity card for that sensor and look at the icon

**Expected behavior**
The entity card should use the icon of the entity.

**Screenshots**
grafik

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Firefox
 - Version 97.0.1

### PR DESCRIPTION
**Pull request by piitaya**
https://github.com/custom-cards/custom-card-helpers is not very active. I imported the icon rules from HA front-end.

fix #87
fix #125 
fix #145

### CODE REVIEW

File: src/utils/icons/alarm-panel-icon.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        case "pending":
+            return "mdi:shield-outline";
+        case "triggered":
+            return "mdi:bell-ring";
+        case "disarmed":
+            return "mdi:shield-off";
+        default:
+            return "mdi:shield";
+    }
+};
```
Comment (piitaya) [inline src/utils/icons/alarm-panel-icon.ts:22]: @bemble Do you think we must replaced our custom alarm panel icon with theses rules ?
```ts 
// from src/cards/alarm-control-panel-card/const.ts
export const ALARM_CONTROL_PANEL_CARD_STATE_ICON = {
    disarmed: "mdi:shield-off-outline",
    arming: "mdi:shield-sync-outline",
    armed_away: "mdi:shield-lock-outline",
    armed_home: "mdi:shield-home-outline",
    armed_night: "mdi:shield-moon-outline",
    armed_vacation: "mdi:shield-airplane-outline",
    armed_custom_bypass: "mdi:shield-half-full",
    pending: "mdi:shield-sync",
    triggered: "mdi:bell-ring-outline",
    unavailable: "mdi:bell-remove-outline",
};
```

Comment (bemble) [reply src/utils/icons/alarm-panel-icon.ts:22]: No prob for me, juste the pending icon, the one I choose is better in my opinion 😛

Comment (piitaya) [reply src/utils/icons/alarm-panel-icon.ts:22]: I will add your unavailable icon too 😊
